name: stash_disk
version: 2.0.0-nullsafety.1
description: >-
  Disk storage extension for the stash caching API. Provides support to store caches
  in the local file system in binary format using the msgpack json format
homepage: https://github.com/ivoleitao/stash_disk

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  path: ^1.8.0
  file: ^6.1.0
  stream_transform: ^2.0.0
  stash: ^2.0.0-nullsafety.2
  # stash:
    # path: ../stash

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.4
  #test_coverage: ^0.4.3
